variables:
  NUGET_PATH: 'C:\Tools\nuget.exe'
  MSBUILD_PATH: 'D:\vs\MSBuild\15.0\Bin\amd64\msbuild.exe'
  PROJ_PATH: 'C:\GitLab-Runner\builds\nToixDBZ\0\khanjason\ac31007Team11\Source` Code\MediSearch\WindowsFormsApp'


stages:
  - build


build_job:
  stage: build
  only:
    - branches
  script:
    - '& cd "$env:PROJ_PATH"'
    - '& "$env:NUGET_PATH" restore "$env:PROJ_PATH"'
    - '& "$env:MSBUILD_PATH" "$env:PROJ_PATH" /p:Configuration=Release /clp:ErrorsOnly'
